### ISSUE TITLE
Broken since today's morning

### ISSUE THREAD

**Issue by tarnos12** [cooljingle/memrise-all-typing#6]
Hello,  

Memrise has made some changes to the object so it no longer works.  

If I had a copy of previously working object, I could fix it maybe.  

Error:  
`TypeError: can't convert undefined to object  Memrise_All_Typing.user.js:175:28`  

Basically a property called "tests" no longer exists on the item, perhaps it is somewhere in the parent object or they changed the structure completely or renamed it.  
Hopefully you can fix it soon, using memrise without this script is a pain.  

Thanks :)

**Comment by cooljingle** [comment]
yeah you were right, they replaced tests with a screens object on the parent.
I've updated the script with the fix (0.1.22).
