### ISSUE TITLE
@match might need to be changed

### ISSUE THREAD

**Issue by tarnos12** [cooljingle/memrise-all-typing#7]
Hello,  

This part:  

// @match          https://www.memrise.com/course/*/garden/*

might need to be change to this:  

// @match          https://www.memrise.com/course/*/*/garden/*  

At least that is the case for me and it works.

**Comment by cooljingle** [comment]
Shouldn't the one used currently already match urls covered by your replacement? As in `/*/` is more general than `/*/*/`.

**Comment by tarnos12** [comment]
https://www.memrise.com/course/1389171/japanese-1/garden/learn/  
https://www.memrise.com/course/554/jlpt-n5-vocab/garden/classic_review/  

Doesn't work when I use /*/  
Maybe it should, I don't know but this problem is something I had since I installed this script, which is like a week ago.

**Comment by tarnos12** [comment]
I am on my laptop now and it seems to be working with a single /*/  
Will see what happens tomorrow, perhaps it was my PC that had some problem.

**Comment by tarnos12** [comment]
It seems to be fine on my laptop, and I can't test it on my PC for few months now.  

The problem was that it wouldn't match the course, so the script was not initialized.  
I have no idea what was the reason but adding /*/*/ on my PC fixed this issue for me.

**Comment by cooljingle** [comment]
According to https://developer.chrome.com/extensions/match_patterns the * should match 0 or more characters. The only way the original pattern wouldn't work would be if the matching rules were different, but I don't see how that could happen.
